server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /_next/ { # keep common patterns open
    try_files $uri $uri/ =404;
  }

  gzip on;
  gzip_types text/plain application/javascript application/json text/css image/svg+xml;
}
